service: jwt-authorizer

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs10.x
  iamRoleStatements:
    - Effect: Allow
      Action:
        - ssm:GetParameter
      Resource:
        - 'Fn::Join':
          - ':'
          - - 'arn:aws:ssm'
            - Ref: 'AWS::Region'
            - Ref: 'AWS::AccountId'
            - 'parameter/jwt-authorizer-${opt:stage, self:provider.stage}/privateKey'

functions:
  jwtAuthorizer:
    handler: dist/index.authorizer
    cors: true
    environment:
      STAGE: ${opt:stage, self:provider.stage}

resources:
  Outputs:
    JwtAuthorizerLambdaFunctionQualifiedArn:
      Export:
        Name: jwtAuthorizer-${file(serverless.js):version}
